[package]
name = 'Userinfo'
version = '1.0.0'

[dependencies.AptosFramework]
Userinfo="_"
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addreses]
sender = "_"